version: "3.8"

services:
  puppeteer-app:
    container_name: puppeteer-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      XDG_CONFIG_HOME: /tmp/.chromium
      XDG_CACHE_HOME: /tmp/.chromium
    working_dir: /usr/src/app
    ports:
      - "4000:4000"
    command: npm start
    restart: unless-stopped
